# Keras and MNIST, MLP

##### From: https://github.com/wxs/keras-mnist-tutorial/blob/master/MNIST%20in%20Keras.ipynb
##### Similar Example: https://github.com/keras-team/keras/blob/master/examples/mnist_mlp.py

In [2]:
#Import necessary libraries

import numpy as np
import keras

from keras.models import Sequential
from keras.layers.core import Dense, Activation, Dropout
from keras.utils import np_utils
from keras.datasets import mnist

/home/kcozart/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

### Step 0: Get Data into Useable Form

In [4]:
# Check x format
print(x_train[:2])

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [5]:
# Check y format -- will need to change
print(y_train[:2])

[5 0]


In [6]:
# We are building our net out of layers
model = Sequential()

In [7]:
# Find the shape of the input
print(x_train.shape)

(60000, 28, 28)


In [8]:
# We need to reshape the data
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')

In [9]:
# Scale inputs by 255
x_train = x_train / 255
x_test = x_test / 255

print(x_train.shape)
print(x_test.shape)

(60000, 784)
(10000, 784)


In [10]:
# We need to get y sets to one-hot-encoded values
def create_one_hot_encoded_array(array):
    uniques, ids = np.unique(array, return_inverse=True)
    return np_utils.to_categorical(ids, len(uniques))

y_train = create_one_hot_encoded_array(y_train)
y_test = create_one_hot_encoded_array(y_test)

print(y_train[:2])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Step 1: Define Network

In [11]:
# We are building our net out of layers
model = Sequential()

In [12]:
# First, we choose dimensionality and then take input shape
# We then add the first layer, which requires input shape info
model.add(Dense(550, input_shape=(784,)))

In [13]:
# Now, we choose an activation function
# This is a non-linear function for classifying
model.add(Activation('relu'))

In [14]:
# We add dropout to stop overfitting
model.add(Dropout(0.2))

In [15]:
# We add another layer with same density
model.add(Dense(550))

In [16]:
# We add the activation functino for this layer
model.add(Activation('relu'))

In [17]:
# Add dropout again
model.add(Dropout(0.2))

In [18]:
# Add dimensionality again, lower this time
model.add(Dense(10))

In [19]:
# For final layer, we want a different activation function
model.add(Activation('softmax'))
# Softmax lets avoid negative values
# Also ensures a valid prob distro where sum is 1

### Step 2: Compile Network

In [20]:
# Optimizer trains the network
# Loss function evaluates the network
# Be sure to add accuracy metric
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

### Step 3: Fit Network

In [21]:
model.fit(x_train, y_train, 
          batch_size=128, epochs=4, verbose=1,
          validation_data=(x_test, y_test)
         )

Train on 60000 samples, validate on 10000 samples
Epoch 1/4
60000/60000 [==============================] - 6s 105us/step - loss: 0.2445 - acc: 0.9266 - val_loss: 0.1054 - val_acc: 0.9665
Epoch 2/4
60000/60000 [==============================] - 5s 88us/step - loss: 0.1006 - acc: 0.9687 - val_loss: 0.0932 - val_acc: 0.9708
Epoch 3/4
60000/60000 [==============================] - 5s 86us/step - loss: 0.0710 - acc: 0.9779 - val_loss: 0.0725 - val_acc: 0.9771
Epoch 4/4
60000/60000 [==============================] - 5s 87us/step - loss: 0.0546 - acc: 0.9830 - val_loss: 0.0624 - val_acc: 0.9820


### Step 4: Evaluate Network

In [22]:
score = model.evaluate(x_test, y_test, verbose=0)
print("Model Accuracy: ", score[1])

Model Accuracy:  0.982
